[package]
version = "1.0.0"
authors = ["NVIDIA"]
title = "Omni UI Scene Prim Widget Controller"
description = "This extension allows programmatic control of 3D widgets on specific prims via prim path and boolean toggle"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/omniverse/kit-extensions/kit-scene"
category = "Documentation"
keywords = ["ui", "example", "scene", "docs", "documentation", "widget", "controller"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.ui.scene" = {  }
"omni.usd" = {  }
"omni.kit.viewport.utility" = {  }

[[python.module]]
name = "omni.example.ui_scene.prim_widget"

[[test]]
args = ["--/renderer/enabled=pxr", "--/renderer/active=pxr", "--no-window"]
dependencies = ["omni.hydra.pxr", "omni.kit.window.viewport"]